taskA:
	clang-format --dry-run -Werror taskA.c
	gcc -std=c99 -Wall -Wextra -Werror taskA.c -o taskA

taskB:
	clang-format --dry-run -Werror taskB.c
	gcc -std=c99 -Wall -Wextra -Werror taskB.c -o taskB

taskC:
	clang-format --dry-run -Werror taskC.c
	gcc -std=c99 -Wall -Wextra -Werror taskC.c -o taskC

taskD:
	clang-format --dry-run -Werror taskD.c
	gcc -std=c99 -Wall -Wextra -Werror taskD.c -o taskD

taskE:
	clang-format --dry-run -Werror taskE.c
	gcc -std=c99 -Wall -Wextra -Werror taskE.c -o taskE

taskF:
	clang-format --dry-run -Werror taskF.c
	gcc -std=c99 -Wall -Wextra -Werror taskF.c -o taskF

taskG:
	clang-format --dry-run -Werror taskG.c
	gcc -std=c99 -Wall -Wextra -Werror taskG.c -o taskG

taskH:
	clang-format --dry-run -Werror taskH.c
	gcc -std=c99 -Wall -Wextra -Werror taskH.c -o taskH

taskI:
	clang-format --dry-run -Werror taskI.c
	gcc -std=c99 -Wall -Wextra -Werror taskI.c -o taskI

taskJ:
	clang-format --dry-run -Werror taskJ.c
	gcc -std=c99 -Wall -Wextra -Werror taskJ.c -o taskJ

taskK:
	clang-format --dry-run -Werror taskK.c
	gcc -std=c99 -Wall -Wextra -Werror taskK.c -o taskK

taskL:
	clang-format --dry-run -Werror taskL.c
	gcc -std=c99 -Wall -Wextra -Werror taskL.c -o taskL

taskM:
	clang-format --dry-run -Werror taskM.c
	gcc -std=c99 -Wall -Wextra -Werror taskM.c -o taskM

taskN:
	clang-format --dry-run -Werror taskN.c
	gcc -std=c99 -Wall -Wextra -Werror taskN.c -o taskN

taskO:
	clang-format --dry-run -Werror taskO.c
	gcc -std=c99 -Wall -Wextra -Werror taskO.c -o taskO

clean:
	rm -f taskA taskB taskC taskD taskE taskF \
	      taskG taskH taskI taskJ taskK \
	      taskM taskO taskL taskN