taskA:
	clang-format --dry-run -Werror taskA.c
	gcc -std=c99 -Wall -Wextra -Werror taskA.c -o taskA

taskB:
	clang-format --dry-run -Werror taskB.c
	gcc -std=c99 -Wall -Wextra -Werror taskB.c -o taskB

taskC:
	clang-format --dry-run -Werror taskC.c
	gcc -std=c99 -Wall -Wextra -Werror taskC.c -o taskC

taskD:
	clang-format --dry-run -Werror taskD.c
	gcc -std=c99 -Wall -Wextra -Werror taskD.c -o taskD

taskE:
	clang-format --dry-run -Werror taskE.c
	gcc -std=c99 -Wall -Wextra -Werror taskE.c -o taskE

clean:
	rm -f taskA taskB taskC taskD taskE